"""esquema inicial 23 tablas

Revision ID: a1557e1dd3bf
Revises: 
Create Date: 2026-07-04 20:08:37.169555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1557e1dd3bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre_categoria')
    )
    op.create_table('categorias_gasto',
    sa.Column('id_categoria_gasto', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria_gasto')
    )
    op.create_table('configuracion',
    sa.Column('id_config', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_config'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('estados_pedido',
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('nombre_estado', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_estado')
    )
    op.create_table('mesas',
    sa.Column('id_mesa', sa.Integer(), nullable=False),
    sa.Column('numero_mesa', sa.Integer(), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), server_default=sa.text("'Disponible'"), nullable=False),
    sa.PrimaryKeyConstraint('id_mesa'),
    sa.UniqueConstraint('numero_mesa')
    )
    op.create_table('metodos_pago',
    sa.Column('id_metodo_pago', sa.Integer(), nullable=False),
    sa.Column('nombre_metodo', sa.String(length=30), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_metodo_pago')
    )
    op.create_table('proveedores',
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('nombre_proveedor', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor')
    )
    op.create_table('roles',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('nombre_rol')
    )
    op.create_table('unidades_medida',
    sa.Column('id_unidad', sa.Integer(), nullable=False),
    sa.Column('nombre_unidad', sa.String(length=30), nullable=False),
    sa.Column('abreviatura', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_unidad')
    )
    op.create_table('insumos',
    sa.Column('id_insumo', sa.Integer(), nullable=False),
    sa.Column('id_unidad', sa.Integer(), nullable=False),
    sa.Column('nombre_insumo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('stock_actual', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidades_medida.id_unidad'], ),
    sa.PrimaryKeyConstraint('id_insumo')
    )
    op.create_index(op.f('ix_insumos_id_unidad'), 'insumos', ['id_unidad'], unique=False)
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre_producto', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('precio_venta', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('disponible', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_producto')
    )
    op.create_index(op.f('ix_productos_id_categoria'), 'productos', ['id_categoria'], unique=False)
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=60), nullable=False),
    sa.Column('apellido_materno', sa.String(length=60), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('contrasena_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('nombre_usuario')
    )
    op.create_index(op.f('ix_usuarios_id_rol'), 'usuarios', ['id_rol'], unique=False)
    op.create_table('compras',
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_compra', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('folio_factura', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedores.id_proveedor'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_compra')
    )
    op.create_index(op.f('ix_compras_id_proveedor'), 'compras', ['id_proveedor'], unique=False)
    op.create_index(op.f('ix_compras_id_usuario'), 'compras', ['id_usuario'], unique=False)
    op.create_table('gastos',
    sa.Column('id_gasto', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_categoria_gasto', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=150), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_gasto', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria_gasto'], ['categorias_gasto.id_categoria_gasto'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_gasto')
    )
    op.create_index(op.f('ix_gastos_id_categoria_gasto'), 'gastos', ['id_categoria_gasto'], unique=False)
    op.create_index(op.f('ix_gastos_id_usuario'), 'gastos', ['id_usuario'], unique=False)
    op.create_table('pedidos',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_mesa', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_estado', sa.Integer(), nullable=False),
    sa.Column('fecha_pedido', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_estado'], ['estados_pedido.id_estado'], ),
    sa.ForeignKeyConstraint(['id_mesa'], ['mesas.id_mesa'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_index(op.f('ix_pedidos_id_estado'), 'pedidos', ['id_estado'], unique=False)
    op.create_index(op.f('ix_pedidos_id_mesa'), 'pedidos', ['id_mesa'], unique=False)
    op.create_index(op.f('ix_pedidos_id_usuario'), 'pedidos', ['id_usuario'], unique=False)
    op.create_table('producto_insumo',
    sa.Column('id_producto_insumo', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_insumo', sa.Integer(), nullable=False),
    sa.Column('cantidad_requerida', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['id_insumo'], ['insumos.id_insumo'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_producto_insumo')
    )
    op.create_index(op.f('ix_producto_insumo_id_insumo'), 'producto_insumo', ['id_insumo'], unique=False)
    op.create_index(op.f('ix_producto_insumo_id_producto'), 'producto_insumo', ['id_producto'], unique=False)
    op.create_table('cancelaciones',
    sa.Column('id_cancelacion', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=False),
    sa.Column('fecha_cancelacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cancelacion'),
    sa.UniqueConstraint('id_pedido')
    )
    op.create_index(op.f('ix_cancelaciones_id_usuario'), 'cancelaciones', ['id_usuario'], unique=False)
    op.create_table('detalle_compra',
    sa.Column('id_detalle_compra', sa.Integer(), nullable=False),
    sa.Column('id_compra', sa.Integer(), nullable=False),
    sa.Column('id_insumo', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), sa.Computed('cantidad * costo_unitario', persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id_compra'], ),
    sa.ForeignKeyConstraint(['id_insumo'], ['insumos.id_insumo'], ),
    sa.PrimaryKeyConstraint('id_detalle_compra')
    )
    op.create_index(op.f('ix_detalle_compra_id_compra'), 'detalle_compra', ['id_compra'], unique=False)
    op.create_index(op.f('ix_detalle_compra_id_insumo'), 'detalle_compra', ['id_insumo'], unique=False)
    op.create_table('detalle_pedido',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), sa.Computed('cantidad * precio_unitario', persisted=True), nullable=True),
    sa.Column('observaciones', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id_producto'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index(op.f('ix_detalle_pedido_id_pedido'), 'detalle_pedido', ['id_pedido'], unique=False)
    op.create_index(op.f('ix_detalle_pedido_id_producto'), 'detalle_pedido', ['id_producto'], unique=False)
    op.create_table('movimientos_inventario',
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('id_insumo', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.Column('id_compra', sa.Integer(), nullable=True),
    sa.Column('tipo_movimiento', sa.String(length=10), nullable=False),
    sa.Column('motivo', sa.String(length=30), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_movimiento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_compra'], ['compras.id_compra'], ),
    sa.ForeignKeyConstraint(['id_insumo'], ['insumos.id_insumo'], ),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_index(op.f('ix_movimientos_inventario_id_compra'), 'movimientos_inventario', ['id_compra'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_id_insumo'), 'movimientos_inventario', ['id_insumo'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_id_pedido'), 'movimientos_inventario', ['id_pedido'], unique=False)
    op.create_index(op.f('ix_movimientos_inventario_id_usuario'), 'movimientos_inventario', ['id_usuario'], unique=False)
    op.create_table('ventas',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('fecha_venta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estado_venta', sa.String(length=20), server_default=sa.text("'Completada'"), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedidos.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_venta'),
    sa.UniqueConstraint('id_pedido')
    )
    op.create_index(op.f('ix_ventas_id_usuario'), 'ventas', ['id_usuario'], unique=False)
    op.create_table('pagos',
    sa.Column('id_pago', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_metodo_pago', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('fecha_pago', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_metodo_pago'], ['metodos_pago.id_metodo_pago'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ),
    sa.PrimaryKeyConstraint('id_pago')
    )
    op.create_index(op.f('ix_pagos_id_metodo_pago'), 'pagos', ['id_metodo_pago'], unique=False)
    op.create_index(op.f('ix_pagos_id_venta'), 'pagos', ['id_venta'], unique=False)
    op.create_table('tickets',
    sa.Column('id_ticket', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('folio', sa.String(length=30), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id_venta'], ),
    sa.PrimaryKeyConstraint('id_ticket'),
    sa.UniqueConstraint('folio'),
    sa.UniqueConstraint('id_venta')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_index(op.f('ix_pagos_id_venta'), table_name='pagos')
    op.drop_index(op.f('ix_pagos_id_metodo_pago'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_ventas_id_usuario'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_movimientos_inventario_id_usuario'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_id_pedido'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_id_insumo'), table_name='movimientos_inventario')
    op.drop_index(op.f('ix_movimientos_inventario_id_compra'), table_name='movimientos_inventario')
    op.drop_table('movimientos_inventario')
    op.drop_index(op.f('ix_detalle_pedido_id_producto'), table_name='detalle_pedido')
    op.drop_index(op.f('ix_detalle_pedido_id_pedido'), table_name='detalle_pedido')
    op.drop_table('detalle_pedido')
    op.drop_index(op.f('ix_detalle_compra_id_insumo'), table_name='detalle_compra')
    op.drop_index(op.f('ix_detalle_compra_id_compra'), table_name='detalle_compra')
    op.drop_table('detalle_compra')
    op.drop_index(op.f('ix_cancelaciones_id_usuario'), table_name='cancelaciones')
    op.drop_table('cancelaciones')
    op.drop_index(op.f('ix_producto_insumo_id_producto'), table_name='producto_insumo')
    op.drop_index(op.f('ix_producto_insumo_id_insumo'), table_name='producto_insumo')
    op.drop_table('producto_insumo')
    op.drop_index(op.f('ix_pedidos_id_usuario'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id_mesa'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id_estado'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_index(op.f('ix_gastos_id_usuario'), table_name='gastos')
    op.drop_index(op.f('ix_gastos_id_categoria_gasto'), table_name='gastos')
    op.drop_table('gastos')
    op.drop_index(op.f('ix_compras_id_usuario'), table_name='compras')
    op.drop_index(op.f('ix_compras_id_proveedor'), table_name='compras')
    op.drop_table('compras')
    op.drop_index(op.f('ix_usuarios_id_rol'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_productos_id_categoria'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_insumos_id_unidad'), table_name='insumos')
    op.drop_table('insumos')
    op.drop_table('unidades_medida')
    op.drop_table('roles')
    op.drop_table('proveedores')
    op.drop_table('metodos_pago')
    op.drop_table('mesas')
    op.drop_table('estados_pedido')
    op.drop_table('configuracion')
    op.drop_table('categorias_gasto')
    op.drop_table('categorias')
    # ### end Alembic commands ###
